---
title: "Visualizations of Senators Dataset"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, cache = T)
```

```{r}
library(MixSim)
library(RColorBrewer)
library(MASS)
library(expm)
library(grDevices)
library(radviz3d)
library(rgl)
library(ggplot2)
library(Rtsne)
library(Rdimtools)
library(uwot)
library(scatterplot3d) 

source("starcoord3d.R")

# color palette
load("colpal.rda")
dk.palette = c(rgb(red = 173, green = 216, blue = 230, max = 255), 
               rgb(max = 255, red = 139, green = 0, blue = 0))

```

```{r}
load("datasets-gdt/senators_normal.rda")
senators_normal_class[35,1] = "D"
senators_normal_class$party <- droplevels(senators_normal_class$party)
sn <- as.matrix(senators_normal_class[,-1])
class <- senators_normal_class$party
sn.df <- data.frame(sn,class)

#df.red <- mrp(data = sn.df[,-543], cl = factor(sn.df[,543]), nproj = 4)$projected_df
#sndf = data.frame(df.red, class)
#save(sndf, file = "datasets/senatordf.rda")
```

<table width="500" border="0" cellpadding="0">

<tr>

<td align="center" valign="center">
```{r}
set.seed(1)
tsne <- Rtsne(as.matrix(sn.df[,-543]), dims = 3, 
              perplexity=min(500,floor((nrow(sn.df)-1)/3)), 
              check_duplicates = F,  
              verbose=F, max_iter = 500)
res1 = tsne$Y
res1 = data.frame(res1, class)
colnames(res1) = c("x","y","z","class")
# open 3d window
 
# resize window
par3d(windowRect = c(100, 100, 612, 612))
# plot
with(res1, plot3d(xlab = "", ylab="", zlab="",axes = F, x,y,z, type="s",size = 0.75,
                  col = dk.palette[1:nlevels(class)][as.numeric(class)]))
box3d()
rgl::rgl.viewpoint(zoom = 0.6)
rglwidget()
```
<br />
(a) t-SNE
</td>

<td align="center" valign="center">
```{r}
set.seed(1)
umap_res <- umap(as.matrix(sn.df[,-543]), n_components =  3, y = sn.df[,543]) 

res1 = data.frame(umap_res, class)
colnames(res1) = c("x","y","z","class")
# open 3d window

# resize window
par3d(windowRect = c(100, 100, 612, 612))
# plot
with(res1, plot3d(xlab = "", ylab="", zlab="",axes = F, x,y,z, type="s",size = 0.75,
                  col = dk.palette[1:nlevels(class)][as.numeric(class)]))
box3d()
rgl::rgl.viewpoint(zoom = 0.6)
rglwidget()
```
<br />
(b) UMAP
</td>
</tr>

<tr>

<td align="center" valign="center">
```{r}
out2 = do.olda(as.matrix(sn.df[,-543]), ndim = 3, class)
senator.olda = data.frame(out2$Y,class)
plot.starcoords2D(senator.olda[,-4], class = senator.olda$class, 
                  colors = dk.palette)
```
<br />
(c) 2D Stars Coordinates with OLDA
</td>

<td align="center" valign="center">
```{r}
out2 = do.ulda(as.matrix(sn.df[,-543]), ndim = 3, class)
senator.ulda = data.frame(out2$Y,class)
plot.starcoords2D(senator.ulda[,-4], class = senator.ulda$class, 
                  colors = dk.palette)
```
<br />
(d) 2D Stars Coordinates with ULDA
</td>
</tr>

<tr>

<td align="center" valign="center">
```{r}
library(readxl)
df <- read_excel("datasets/senate_voting_data.xls")
names <- colnames(df)[-(1:2)]
names <- sub(" \\(.*", "", names)
names <- sub(".* ", "", names)

df.red <- mrp(data = sn.df[,-543], cl = factor(sn.df[,543]), nproj = 2)$projected_df[,1:2]
colnames(df.red) <- c("mrp1","mrp2")
df.red$class <- sn.df$class
df.red$names <- names

idx <- which((df.red$mrp1 > -6) & (df.red$mrp1 < 7.5))

p <- ggplot(df.red, aes(x = mrp1, y = mrp2, pch = class, color = class)) + 
  geom_point() + 
  theme_light() + theme(legend.position = "none") + 
    labs(x = "MRP 1", y = "MRP 2") +
    scale_shape_manual(values=17:16) +
    scale_color_manual(values=dk.palette) +
  geom_text(aes(x = mrp1[idx[1]], y = mrp2[idx[1]]+2), 
                      label = names[idx[1]], color = "black") +
  geom_text(aes(x = mrp1[idx[2]], y = mrp2[idx[2]]+2), 
                      label = names[idx[2]], color = "black") +
  geom_text(aes(x = mrp1[idx[3]], y = mrp2[idx[3]]+2), 
                      label = names[idx[3]], color = "black") +
  geom_text(aes(x = mrp1[idx[4]], y = mrp2[idx[4]]+2), 
                      label = names[idx[4]], color = "black") +
  geom_text(aes(x = mrp1[idx[5]], y = mrp2[idx[5]]+2), 
                      label = names[idx[5]], color = "black") +
  geom_text(aes(x = mrp1[idx[6]], y = mrp2[idx[6]]+2), 
                      label = names[idx[6]], color = "black") +
  geom_text(aes(x = mrp1[idx[7]], y = mrp2[idx[7]]+2), 
                      label = names[idx[7]], color = "black") +
  geom_text(aes(x = mrp1[idx[8]], y = mrp2[idx[8]]+2), 
                      label = names[idx[8]], color = "black") +
  geom_text(aes(x = mrp1[idx[9]], y = mrp2[idx[9]]+2), 
                      label = names[idx[9]], color = "black") +
  geom_text(aes(x = mrp1[idx[10]], y = mrp2[idx[10]]+2), 
                      label = names[idx[10]], color = "black") +
  geom_text(aes(x = mrp1[idx[11]], y = mrp2[idx[11]]+2), 
                      label = names[idx[11]], color = "black") +
  geom_text(aes(x = mrp1[idx[12]], y = mrp2[idx[12]]+2), 
                      label = names[idx[12]], color = "black") 
p
```
<br />
(e) 2D Scatter Plot
</td>

<td align="center" valign="center">
```{r}
df.red <- mrp(data = sn.df[,-543], cl = factor(sn.df[,543]), nproj = 3)$projected_df
scatterplot3d(df.red, pch = (20:1)[as.numeric(class)],
                     color = dk.palette[as.numeric(class)], 
                     xlab = "",  ylab = "", zlab = "", box = F,
                     grid = T, tick.marks = F, label.tick.marks = F)
```
<br />
(f) 3D Scatter Plot
</td>
</tr>

<tr>

<td align="center" valign="center">
```{r}
load("datasets/senatordf.rda")
plot.starcoords3D(data = sndf[,-5], pradius = 0.02, class = factor(sndf[,5]), 
                  colors = dk.palette)
rgl::rgl.viewpoint(zoom = 0.6)
rglwidget()
```
<br />
(g) Starcoords3D
</td>
</tr>
</table>
