---
title: "t-SNE: 4 Groups"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(MixSim)
library(RColorBrewer)
library(MASS)
library(expm)
library(grDevices)
library(rgl)
library(radviz3d)
library(Rtsne)

```


```{r, echo=F}
set.seed(2022)
res_tsne <- list()
sim.palette <- brewer.pal(8,"Dark2")[c(5,8,4,7)]
load("sim_data_100_4g.rda")
for (i in 1:3){
  df <- sim_data[[i]]
  df.gdt <- radviz3d::Gtrans(df[,-1])
  class <- df$class
  tsne <- Rtsne(as.matrix(df.gdt), dims = 3, 
              perplexity=min(500,floor((nrow(df)-1)/3)), 
              check_duplicates = F,  
              verbose=F, max_iter = 500)
  res1 = tsne$Y
  res1 = data.frame(res1, class)
  colnames(res1) = c("x","y","z","class")
  # open 3d window
 
  # resize window
  par3d(windowRect = c(100, 100, 612, 612))
  # plot
  with(res1, plot3d(xlab = "", ylab="", zlab="",axes = F, x,y,z, type="s", size = 0.75,
                    col = sim.palette[1:nlevels(class)][as.numeric(class)]))
  box3d()
  rgl::rgl.viewpoint(zoom = 0.6)
  res_tsne[[i]] <- rgl::rglwidget()
}

```


<table width="500" border="0" cellpadding="0">


<tr>
<td align="center" valign="center">
```{r}
res_tsne[[1]]
```
(i) t-SNE, $p = 100, \ddot\omega = 0.001$ 
<br />
</td>

</tr>
</tr>

<td align="center" valign="center">
```{r}
res_tsne[[2]]
```
(ii) t-SNE, $p = 100, \ddot\omega = 0.01$ 
<br />
</td>

</tr>
</tr>

<td align="center" valign="center">
```{r}
res_tsne[[3]]
```
(iii) t-SNE, $p = 100, \ddot\omega = 0.05$
<br />
</td>

</tr>
</table>